// controllers/chatbot_controller.go

package controllers

import (
	"fmt"
	"net/http"
	"os/exec"
	"strings"

	"github.com/gin-gonic/gin"
)

// RunChatbot is the handler for the API call.
func GetChatbotResponse(c *gin.Context) {
	// Get the input text from the request body
	var request struct {
		InputText string `json:"inputText"`
	}
	if err := c.ShouldBindJSON(&request); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// Run the Python script as a subprocess
	cmd := exec.Command("python3", "./chatbot/main.py", request.InputText)

	// Capture the output of the Python script
	output, err := cmd.CombinedOutput()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Error executing Python script"})
		return
	}

	// Print the output generated by the Python script
	fmt.Println("Python script output:", string(output))

	// Return the output as the API response
	c.JSON(http.StatusOK, gin.H{"output": strings.TrimSpace(string(output))})
}
