// controllers/user_controller.go
package controllers

import (
	"context"
	"net/http"

	"Server/db"
	"Server/models"
	"Server/utils" // Import the utils package

	"firebase.google.com/go/auth"
	"github.com/gin-gonic/gin"
	"google.golang.org/api/iterator"
)

const usersCollection = "users"

var ctx = context.Background()

func SignupUser(c *gin.Context) {
	// Bind JSON request body to the user model
	var user models.User
	if err := c.ShouldBindJSON(&user); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// Hash the user's password
	hashedPassword, err := utils.HashPassword(user.PasswordHash)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to hash password"})
		return
	}

	// Set the hashed password in the user model
	user.PasswordHash = hashedPassword

	// Create user in Firebase Authentication
	params := (&auth.UserToCreate{}).
		Email(user.Email).
		Password(user.PasswordHash).
		DisplayName(user.Profile.FirstName + " " + user.Profile.LastName).
		Disabled(false)

	userRecord, err := db.AuthClient.CreateUser(ctx, params)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create user in Firebase Authentication"})
		return
	}

	// Set the AuthID field of the user model to the UID generated by Firebase Authentication
	user.AuthID = userRecord.UserInfo.UID

	// Create user in Firestore and let Firestore generate the ID
	docRef, _, err := db.FirestoreClient.Collection(usersCollection).Add(ctx, user)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create user in Firestore"})
		return
	}

	// Set the ID field of the user model to the UID generated by Firestore
	user.ID = docRef.ID

	// Update the user document in Firestore with the user ID
	_, err = docRef.Set(ctx, user)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to update user ID in Firestore"})
		return
	}

	c.JSON(http.StatusCreated, gin.H{"message": "User created successfully", "id": docRef.ID})
}

func LoginUser(c *gin.Context) {
	var credentials struct {
		Email    string `json:"email"`
		Password string `json:"password"`
	}

	if err := c.ShouldBindJSON(&credentials); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// Retrieve user by email
	user, err := getUserByEmail(credentials.Email)
	if err != nil {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "Invalid email"})
		return
	}

	// Compare hashed password using the function from the utils package
	if err := utils.ComparePasswords(user.PasswordHash, credentials.Password); err != nil {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "Incorrect password"})
		return
	}

	// Authentication successful
	c.JSON(http.StatusOK, gin.H{"message": "Login successful", "user": user})
}

func GetUser(c *gin.Context) {
	userID := c.Param("id")

	doc, err := db.FirestoreClient.Collection(usersCollection).Doc(userID).Get(context.Background())
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "User not found"})
		return
	}

	var user models.User
	doc.DataTo(&user)

	c.JSON(http.StatusOK, user)
}

func GetUsers(c *gin.Context) {
	var users []models.User

	iter := db.FirestoreClient.Collection(usersCollection).Documents(context.Background())
	for {
		doc, err := iter.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to retrieve users"})
			return
		}

		var user models.User
		doc.DataTo(&user)
		users = append(users, user)
	}

	c.JSON(http.StatusOK, users)
}

func UpdateUser(c *gin.Context) {
	userID := c.Param("id")

	var updatedFields map[string]interface{}
	if err := c.ShouldBindJSON(&updatedFields); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// Check if the user exists
	userRef := db.FirestoreClient.Collection(usersCollection).Doc(userID)
	docSnapshot, err := userRef.Get(context.Background())
	if err != nil {
		if err == iterator.Done {
			c.JSON(http.StatusNotFound, gin.H{"error": "User not found"})
			return
		}
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to retrieve user"})
		return
	}

	// Merge the existing user data with the updated fields
	var existingUser models.User
	docSnapshot.DataTo(&existingUser)
	for key, value := range updatedFields {
		switch key {
		case "firstName":
			existingUser.Profile.FirstName = value.(string)
		case "lastName":
			existingUser.Profile.LastName = value.(string)
		case "dob":
			existingUser.Profile.Dob = value.(string)
		case "profileImage":
			existingUser.Profile.ProfileImage = value.(string)
			// Add more cases for other fields you want to update
		}
	}

	// Update the user in Firestore
	_, err = userRef.Set(context.Background(), existingUser)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to update user"})
		return
	}

	c.JSON(http.StatusOK, gin.H{"message": "User updated successfully"})
}

func DeleteUser(c *gin.Context) {
	userID := c.Param("id")

	// Retrieve the user document from Firestore to get the AuthID
	userDoc, err := db.FirestoreClient.Collection(usersCollection).Doc(userID).Get(context.Background())
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to retrieve user from Firestore"})
		return
	}

	var user models.User
	if err := userDoc.DataTo(&user); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to parse user data from Firestore"})
		return
	}

	// Delete user from Authentication using AuthID
	err = db.AuthClient.DeleteUser(context.Background(), user.AuthID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to delete user from Authentication"})
		return
	}

	// Delete the user document from Firestore
	_, err = db.FirestoreClient.Collection(usersCollection).Doc(userID).Delete(context.Background())
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to delete user from Firestore"})
		return
	}

	c.JSON(http.StatusOK, gin.H{"message": "User deleted successfully"})
}

func AddToFavorites(c *gin.Context) {
	userID := c.Param("id")
	articleID := c.Query("articleID")

	// Retrieve the user document
	userRef := db.FirestoreClient.Collection(usersCollection).Doc(userID)
	docSnapshot, err := userRef.Get(context.Background())
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to retrieve user"})
		return
	}

	var user models.User
	if err := docSnapshot.DataTo(&user); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to parse user data"})
		return
	}

	// Add the article ID to favorites
	user.FavouriteArticles = append(user.FavouriteArticles, articleID)

	// Update the user document in Firestore
	_, err = userRef.Set(context.Background(), user)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to update user"})
		return
	}

	c.JSON(http.StatusOK, gin.H{"message": "Article added to favorites successfully"})
}

func RemoveFromFavorites(c *gin.Context) {
	userID := c.Param("id")
	articleID := c.Query("articleID")

	// Retrieve the user document
	userRef := db.FirestoreClient.Collection(usersCollection).Doc(userID)
	docSnapshot, err := userRef.Get(context.Background())
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to retrieve user"})
		return
	}

	var user models.User
	if err := docSnapshot.DataTo(&user); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to parse user data"})
		return
	}

	// Check if the article is in favorites
	var isFavorite bool
	var updatedFavorites []string
	for _, favArticleID := range user.FavouriteArticles {
		if favArticleID == articleID {
			isFavorite = true
		} else {
			updatedFavorites = append(updatedFavorites, favArticleID)
		}
	}

	// If the article is not in favorites, return an error
	if !isFavorite {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Article is not in favorites"})
		return
	}

	// Update the user's favorites list without the removed article
	user.FavouriteArticles = updatedFavorites

	// Update the user document in Firestore
	_, err = userRef.Set(context.Background(), user)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to update user"})
		return
	}

	c.JSON(http.StatusOK, gin.H{"message": "Article removed from favorites successfully"})
}

func getUserByEmail(email string) (*models.User, error) {
	query := db.FirestoreClient.Collection(usersCollection).Where("Email", "==", email)
	iter := query.Documents(context.Background())

	doc, err := iter.Next()
	if err == iterator.Done {
		return nil, err
	}
	if err != nil {
		return nil, err
	}

	var user models.User
	doc.DataTo(&user)
	return &user, nil
}
